### PR TITLE
✨ Support upload YouTube shorts

### PR DESCRIPTION
**Pull request by ibra-hassan**

### CODE REVIEW

**Review by nawfelsekrafi — COMMENTED** [review]
looks good to me

**Comment by nawfelsekrafi** [comment]
@ibra-hassan  please resolve the conflicts that has been occurred ..

**Comment by nawfelsekrafi** [comment]
@luin please check this after conflicts are resolved.. it contains a minor changes.

**Comment by ibra-hassan** [comment]
Hi @nawfelsekrafi 

I'm sorry for the confusion, but I created a new PR.

https://github.com/slab/quill/pull/4345

**Pull request closed without merging**
